on:
  release:
    types: [published]

name: Docker

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Login Docker
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set git env
        run: |
          echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Make envfile
        run: |
          cat > .env.production
          echo "VITE_API_URL=/api/ >> ..env.production
          echo "VITE_STRIPE_P_KEY=${{ secrets.STRIPE_P_KEY }}" >> ..env.production
          echo "VITE_VERSION=${{ env.TAG_NAME }}" >> ..env.production
          echo "VITE_V_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> ..env.production
          echo "$(<.env.production)"

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 18.16

      - name: Install depends
        run: |
          yarn --ignore-scripts

      - name: Build
        run: |
          yarn build

      - name: Build and Push Docker Image
        run: |
          docker build ./API -t ${{ vars.REPOSITORY_NAME }}:${{ env.TAG_NAME }} 
          docker push ${{ vars.REPOSITORY_NAME }}:${{ env.TAG_NAME }}
